theme: minima
title: Pytest
author: Karthik
email: karthikb35@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Pytest learnings
  
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  karthikb35
facebook_username: test

show_excerpts: true # set to false to remove excerpts on the homepage
